obj-$(CONFIG_FIH_INFO) += fih_info.o
obj-$(CONFIG_FIH_UFS) += fih_ufs.o
obj-$(CONFIG_FIH_TOUCH) += fih_touch.o
obj-$(CONFIG_FIH_NV) += fih_nv_cust.o
obj-$(CONFIG_FIH_NV) += fih_nv_def.o
obj-$(CONFIG_FIH_NV) += fih_nv_rf.o
obj-$(CONFIG_FIH_MFR) += fih_mfr.o
